sonar.projectKey=anoopkum_enterprise-ai-agents
sonar.projectName=enterprise-ai-agents
sonar.organization=anoopkum

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
